### ISSUE TITLE
Merge functionality of RawReverseFFT and ReverseFFT

### ISSUE THREAD

**Issue by psurukuc** [project8/locust_mc#116]
The current functionality of ReverseFFT in ComplexFFT could be generalized to include a generic forward and reverse FFT functionality that could be used for any kind of Fourier and reverse Fourier transforms to be used in Locust. Currently, the IFFT (i.e., reverse FFT ) only generates the real part and not the imaginary part. The other parts that could have improvements include generalizing the prebuffer size, the window size, and the zero-padding size.

**Comment by pslocum** [comment]
This is addressed in https://github.com/project8/locust_mc/pull/165 .
