### ISSUE TITLE
Make Install Error

### ISSUE THREAD

**Issue by spforster13** [project8/locust_mc#191]
When running the _make install_ command the following error comes up:

_[ 97%] Linking CXX shared library libLocustMC.dylib
Undefined symbols for architecture x86_64:
  "long boost::math::ltrunc<double>(double const&)", referenced from:
      boost::math::detail::cubic_b_spline_imp<double>::operator()(double) const in LMCPatchAntenna.cc.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [Source/libLocustMC.dylib] Error 1
make[1]: *** [Source/CMakeFiles/LocustMC.dir/all] Error 2
make: *** [all] Error 2_

This issue is caused by the code not pulling a Boost code in the file LMCPatchAntenna.  The fix for this issue is to add the following include statement to the beginning of the file:

_#include <boost/math/special_functions/trunc.hpp>_

Once added the  _make install_ command is able to fully run to 100%.

**Comment by pslocum** [comment]
Thanks for the fix.  This is now merged in https://github.com/project8/locust_mc/commit/1ecbcd3310d99ec429d57b423462a306c0e2653e .
