### ISSUE TITLE
Bug fix with the number of samples in FIR filter

### ISSUE THREAD

**Issue by psurukuc** [project8/locust_mc#208]
This line [here](https://github.com/project8/locust_mc/blob/cc8faf3ffed7647d59831c85ead98d824b795910/Source/Core/LMCHFSSResponseFileHandler.cc#L112) has to be fixed to say
fFIRNBins=2*fTFNBins+fComplexFFT.GetShiftNBins()
instead of
fFIRNBins=fTFNBins+2*fComplexFFT.GetShiftNBins();
to be consistent with [here](https://github.com/project8/locust_mc/blob/cc8faf3ffed7647d59831c85ead98d824b795910/Source/Transforms/LMCComplexFFT.cc#L238)

FIRs are typically long enough that it shouldn’t be a problem but it would be good to fix for consistency.

**Comment by arinabykadorova** [comment]
After some experimentation, it appears that the longer FIR length, 2*fComplexFFT.GetShiftNBins() is better for the antenna response. This has been addressed in the hotfix/FIR_length branch by changing LMCComplex.cc.
