### ISSUE TITLE
Threads (Rarely) Hang on Startup, some OSes 

### ISSUE THREAD

**Issue by buzinsky** [project8/locust_mc#29]
Increasing sleep time is foolproof, though aesthetically unappealing. See if possible to use thread library functions to avoid this locking up all the time.

**Comment by pslocum** [comment]
This issue may be addressed with the proposed 2-way trigger and related suggestions, here:  https://github.com/project8/locust_mc/issues/246 .  Suggesting to close this as an effective merge with https://github.com/project8/locust_mc/issues/246 .  If new relevant information becomes available, please open a new issue and link to this one for history and tracking.
