### ISSUE TITLE
Segmentation violation when using shrink_to_fit on unused buffer

### ISSUE THREAD

**Issue by psurukuc** [project8/locust_mc#71]
In antenna_signal_generator branch, the program seg faults when performing `pop_front` and subsequent `shrink_to_fit` on the unused `ConvolutionTimeBuffer` (an std:::deque) in [LMCDipoleSignalGenerator](https://github.com/project8/locust_mc/blob/feature/antenna_signal_generator/Source/Generators/LMCDipoleSignalGenerator.cc). This issue has also been noticed by @pslocum in the develop branch.

**Comment by pslocum** [comment]
Closing this for now due to removal of unused buffers.  We should still confirm optimal memory handling of deque buffers.
