### ISSUE TITLE
Combine functionality for several generators that use similar functionality

### ISSUE THREAD

**Issue by psurukuc** [project8/locust_mc#72]
Several generators like [DipoleSignalGenerator](https://github.com/project8/locust_mc/blob/feature/antenna_signal_generator/Source/Generators/LMCDipoleSignalGenerator.cc), [PlaneWaveGenerator](https://github.com/project8/locust_mc/blob/feature/antenna_signal_generator/Source/Generators/LMCPlaneWaveSignalGenerator.cc), and [PatchSignalGenerator](https://github.com/project8/locust_mc/blob/develop/Source/Generators/LMCPatchSignalGenerator.cc) have a decent amount repition in code. This can be combined in some form.

**Comment by pslocum** [comment]
I would like to start unifying transmitter classes for selection by parameter with the LMCArraySignalGenerator class.  So we would have one generator and several LMCTransmitter subclasses.

**Comment by pslocum** [comment]
Repetition in code has been reduced.  We should reopen this issue if repetition appears again.
