### ISSUE TITLE
Implement a separate class for FIR functionality 

### ISSUE THREAD

**Issue by psurukuc** [project8/locust_mc#73]
A narrower enhancement within a broad scope of combining functionality of multiple generators as described in [this ](https://github.com/project8/locust_mc/issues/72) issue.
A separate class could be implemented within the `/Core` directory to have FIR filter functionality where each object has an associated FIR file where an FIR Filter is stored.
The attributes of the class could be:
`FIRFileName (std::string)`
`FIRFilter (std::vector)`
`FIRFilterSize (int)`
etc.

In addition, the functionality (similar to what already exists in the [FieldEstimator](https://github.com/project8/locust_mc/blob/feature/antenna_signal_generator/Source/Transmitters/LMCFieldEstimator.cc)) to convolve a given field/voltage with the FIR filter could also be implemented within the class.

**Comment by psurukuc** [comment]
A minimal class now exists in core/LMCFIRHandler.hh/.cc

**Comment by pslocum** [comment]
This is great.  Are the new files pushed to the remote branch yet?  I am
looking in feature/CodeUnification.

**Comment by psurukuc** [comment]
Penny,

They are in core directory.
https://github.com/project8/locust_mc/blob/feature/CodeUnification/Source/Core/LMCFIRHandler.hh

Pranava Teja Surukuchi
__________________________________
Postdoctoral Research Associate
Wright laboratory, Yale university
Email: pranavateja.surukuchi@yale.edu

**Comment by psurukuc** [comment]
I think the files were missed in a previous iteration.

Pranava Teja Surukuchi
__________________________________
Postdoctoral Research Associate
Wright laboratory, Yale university
Email: pranavateja.surukuchi@yale.edu

**Comment by pslocum** [comment]
Found them, thanks.

**Comment by pslocum** [comment]
Tested and merged to develop.
