### ISSUE TITLE
Make global functions in PatchSignalGenerator into class functions

### ISSUE THREAD

**Issue by psurukuc** [project8/locust_mc#74]
Replace global functions in [PatchSignalGenerator](https://github.com/project8/locust_mc/blob/develop/Source/Generators/LMCPatchSignalGenerator.cc) with class functions so as to not have conflicts between the functionality of overridden classes.

**Comment by pslocum** [comment]
This is now complete with the exception of free-field solution functions and signal combining functions, both of which will be moved into planned new classes.
